version: '3'
    
services:
  flask:
    build: ./flask
    image: flask_app
    command: gunicorn -w 3 -t 60 -b 0.0.0.0:8000 app:app
    labels:
      - "traefik.enable=true"
      - "traefik.backend=flask"
      - "traefik.frontend.rule=Host: $DOMAIN_NAME, www.$DOMAIN_NAME"
      - "traefik.port=8000"

  traefik:
    image: traefik:1.7-alpine
    environment:
      - DOMAIN_NAME=$DOMAIN_NAME
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.toml:/etc/traefik/traefik.toml:ro
      - ./traefik/acme:/etc/traefik/acme
      - ~/.htpasswd:/etc/htpasswd/.htpasswd
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host: monitor.$DOMAIN_NAME"
      - "traefik.port=8080"
    ports:
     - "80:80"
     - "443:443"
