version: '2'
services:
  flask:
    build: ./flask
    image: flask
    command: gunicorn -w 3 -t 60 -b 0.0.0.0:5000 app:app
    labels:
      - "traefik.enable=true"
      - "traefik.backend=flask"
      - "traefik.frontend.rule=Host: classifier-web.com, www.classifier-web.com"
  traefik:
    image: traefik:v1.7.16
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.toml:/etc/traefik/traefik.toml:ro
      - ./traefik/acme:/etc/traefik/acme
    ports:
     - "80:80"
     - "443:443"
     - "8080:8080"
